### PR TITLE
Rotate the board

### PR DESCRIPTION
**Pull request by Adpbonar**

### CODE REVIEW

**Comment by freshcup** [comment]
Good work. I am excited to test this out.

**Comment by Adpbonar** [comment]
The flip function is not as elegant as I would like, but it works

**Comment by StephenMelnick** [comment]
Hey there is a merge conflict and I don't exactly know what to remove / keep and it's stopping me from doing the pull... I'm sure you know better than me what to keep / remove could you run through the 2 conflicts?...Cool work I was just wondering if this will cause any issues with the index values... for example if the pawn is still in it's starting position it can move 2 squares... is this purely just visual on our end? What happens when pieces are being moved the board is updating and refreshing?

**Comment by Adpbonar** [comment]
It shouldn't cause issues with the index values. It is just rotating the various components through DOM manipulation.

That said, I can go through the conflicts.

**Pull request merged**
